### ISSUE TITLE
Seaborn is not installed as dependency

### ISSUE THREAD

**Issue by vinferrer** [ME-ICA/aroma#19]
### Summary
I was trying the plotting part and seaborn was not installed in my computer i checked and is not in the ``setup.cfg``

### Next Steps
- add seaborn to the installation dependecies

**Comment by tsalo** [comment]
Per #10, I think we should make all plotting truly optional, with a specific plotting-related dependency set. We can address this bug and my proposal in the same PR.

**Comment by vinferrer** [comment]
okay

**Comment by vinferrer** [comment]
I think we can close  this, once we merge #35
