### ISSUE TITLE
CLI error: folder does not exist

### ISSUE THREAD

**Issue by eurunuela** [ME-ICA/aroma#21]
### Summary

Running aroma from the command line raises a `The folder does not exist` error.

### Additional Detail

Command I ran:

`aroma -i sub-pixar123_task-pixar_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz -tr 2 -out out -mc mc.tsv `

Error I got:

```bash
usage: aroma [-h] -o OUT_DIR (-i IN_FILE | -f IN_FEAT) [-mc MC] [-a AFFMAT] [-w WARP] [-m MASK]
             [-tr TR] [-den {nonaggr,aggr,both,no}] [-md MEL_DIR] [-dim DIM] [-ow] [-np]
aroma: error: The folder  does not exist!
```

### Next Steps

The error is raised by the following line in àroma/cli/aroma.py`:

`options = _get_parser().parse_args(argv)`

**Comment by eurunuela** [comment]
I've tracked this down and the problem comes from the following line:

`type=lambda x: is_valid_path(parser, x)`

which only exists for the melodic folder and the feat folder options.

We will have to make the defaults `None` and only check if the file exists when the variable is not `None`.

**Comment by tsalo** [comment]
That should be pretty straightforward. I'm a little surprised that it raises an error when the parameters aren't actually set though..

EDIT: Never mind, I understand. It's just that the defaults are bad, not that the `is_valid_path` function is.

**Comment by eurunuela** [comment]
> EDIT: Never mind, I understand. It's just that the defaults are bad, not that the `is_valid_path` function is.

That's what I meant, yes. I'm surprised though. And we did not catch this because the integration error does not call the command line.
