### ISSUE TITLE
Generate a benchmark dataset for the features module

### ISSUE THREAD

**Issue by oesteban** [ME-ICA/aroma#32]
Steps:

1. Modify the ICA-AROMA code, making sure all intermediate results are not wiped out.
1. Run that derived code from ICA-AROMA locally with FSL installed
1. Create a zipfile with intermediate results, including all the masks generated along the way as well as the conversion (resampling) of the initial BOLD in standard space. Make sure all the masks that the feature extraction requires are all kept in the standard space. Include in the zip the dataframe of features you obtain (could be done together with #31)
1. Write unit tests of the features module using these masks.

**Comment by oesteban** [comment]
It would be interesting that this dataset and #29 were the same so that when we take the leap of working on native space it is easy to adjust the new thresholds to obtain close results.

**Comment by eurunuela** [comment]
I would stick to one single dataset for all tests if possible. One in native space, one in MNI space.

**Comment by oesteban** [comment]
I think @tsalo would very much appreciate having this ready for when he starts hacking today. Unfortunately, I don't have the bandwidth to do it today - @eurunuela do you think you could find someone to get this done soonish?

**Comment by eurunuela** [comment]
I can try to do it myself. I'll see if I find enough time for this.

**Comment by oesteban** [comment]
Yup, considering the momentum @tsalo is showing, I think anything we can do to cater to him will get us a long way.

**Comment by eurunuela** [comment]
I completely agree! He's on 🔥 !
