### ISSUE TITLE
Transfer ownership to ME-ICA organization

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/aroma#38]
### Summary
This came up in today's `tedana` devs call. We think that it might make it easier to continue development of the AROMA refactor if it's under the ME-ICA organization.

**Comment by eurunuela** [comment]
Well, it's done! We're going to have to make sure CircleCI and Codecov still work.

**Comment by eurunuela** [comment]
> Well, it's done! We're going to have to make sure CircleCI and Codecov still work.

#39 took care of this. Closing this issue.
