### ISSUE TITLE
Change testing docker image

### ISSUE THREAD

**Issue by vinferrer** [ME-ICA/aroma#49]
### Summary

We should change the docker image for the testing since we are not using fsl anymore.

### Next Steps
1. Chose new image (miniconda?)
2. Implement necessary changes in config.ylm
3. Check tests work in the new image

**Comment by eurunuela** [comment]
This makes sense now that #48 was merged. It should make the testing way faster.

**Comment by vinferrer** [comment]
I am planning to make it a PR for hacktoberfest
