### ISSUE TITLE
Integration test artifacts are not being stored

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/aroma#50]
### Summary
This stems from https://github.com/ME-ICA/aroma/pull/46#issuecomment-931394320. Basically, the path we use in the CircleCI config for `store_artifacts` isn't where the integration tests are writing their outputs to, which means we can't access those outputs.

### Next Steps
1. Figure out the appropriate output directory to use in the integration test.
2. Use that path.
3. Ensure that `store_artifacts` is also pointing to that directory.
4. Check that artifacts are accessible.

**Comment by vinferrer** [comment]
I think the issue arises from this `fixture`in `conftest.py`:
```
@pytest.fixture(scope="session")
def testpath(tmp_path_factory):
    """Test path that will be used to download all files."""
    return tmp_path_factory.getbasetemp()
```
This function generates a random `dir` to download the data, we could instead just define the directory as `/tmp/data`
