### ISSUE TITLE
Brainhack Donostia 2021

### ISSUE THREAD

**Issue by eurunuela** [ME-ICA/aroma#54]
### Summary

This issue aims to host a list of tasks/goals for Brainhack Donostia 2021.

As of the start of Brainhack Donostia 2021, we have 11 issues and 5 PRs open. I have added labels to the open issues to indicate the necessary effort, the impact, and the priority of closing them. Feel free to adjust them if they do not seem realistic.

There are also a few issues labeled `Good First Issue` that should be quite straightforward to get done:

#3 , #42 and #44 (this one actually has PR #45 open).

At the same time, we should try to close the PRs we have open, especially #22 , #28 and #46 . I believe it would be great if we could merge these 3 PRs.

What do you think @tsalo @handwerkerd ?

**Comment by tsalo** [comment]
I agree with all of it except probably #22. I never could figure out how to do mixture modeling the MELODIC way in Python, so unless there's a new implementation that popped up somewhere else that we can use... I'm not sure what to do there.

**Comment by eurunuela** [comment]
> I agree with all of it except probably #22. I never could figure out how to do mixture modeling the MELODIC way in Python, so unless there's a new implementation that popped up somewhere else that we can use... I'm not sure what to do there.

Without having checked any of it, I'll say I'm optimistic @cesarcaballerogaudes and I can figure it out 😆

**Comment by tsalo** [comment]
Okay, #22 has been merged into the new `mixture` branch, so you can open a PR from `mixture` to `main` when you plan on tackling pure Python ICA.

**Comment by CesarCaballeroGaudes** [comment]
> > I agree with all of it except probably #22. I never could figure out how to do mixture modeling the MELODIC way in Python, so unless there's a new implementation that popped up somewhere else that we can use... I'm not sure what to do there.
> 
> Without having checked any of it, I'll say I'm optimistic @CesarCaballeroGaudes and I can figure it out 😆

Yes, we can try, but personally I would focus on #28 (as well as the ICA-AROMA code)

**Comment by handwerkerd** [comment]
I don't have a huge amount to add at this point. Of the open PRs, #24 is the one that interests me the most, but I know that it's an enhancement that depends on getting everything else working.

I'm not going to be awake during most of the core Brainhack Donostia hours, but I'll try to be responsive to questions and ideas during other hours. These days are a bit busy for me, but let me know if a PR could use an hour or so of my review time.
