### ISSUE TITLE
Sphinx documentation

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/aroma#8]
### Summary
Do we want to develop Sphinx-based documentation?

### Additional Detail
We can build our documentation on a ReadTheDocs site, but I'm not sure if we want to do that in _this_ repository or in a new repo that wasn't created for a demonstration.

### Next Steps
1. Copy documentation structure from an existing library (e.g., `tedana`, `NiMARE`, or `phys2bids`).
2. Adapt documentation to fit AROMA.
3. Set up RTD site.

**Comment by eurunuela** [comment]
> You might want to have some barebones installation of sphinx here, so that the developer API can be generated from the docstrings easily and do not spend too much time with finicky RTD installations (e.g., cloning this repo for the docstrings from the tutorial's repo build).

That's a good idea. If we can generate part of the documentation with the docstrings that would be great. I will have a look at how you deal with this on `fMRIPrep` for example.

**Comment by oesteban** [comment]
With sphinx + autodoc (which is an extension distributed with the sphinx package itself) it should be fairly easy. We use sphinx-napoleon to allow numpy-style docstrings easily.

**Comment by eurunuela** [comment]
I like numpy-style docstrings and think we should have those here too. Thank you Óscar, I'll have a look!
